server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true

eureka:
  instance:
    hostname: webhook-service
    prefer-ip-address: true
  client:
    register-with-eureka: true

    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li6ROKOgMYOPi707
            client-secret: f45edbc188ee561f73f0b886625e0f8a427448a4
            scope: read:user,repo,admin:repo_hook
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5433/auth_db
    username: najim
    password: najim
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true