server:
  port: 8999
spring:
  data:
    mongodb:
      uri:   mongodb://najim:najim@mongo_db:27017/webhook_db?authSource=admin
#  kafka:
#    bootstrap-servers: kafka:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  instance:
    hostname: webhook-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka



