spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: najim
    password: najim
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true