spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: webhook-service
  mongodb:
    host: localhost
    port: 27017
    username: najim
    password: najim
    database: webhook_db
    authentication-database: admin